version: '3.7'

x-environment:
    &default-environment
    MYSQL_USER: vscode
    MYSQL_PASSWORD: vscode
    MYSQL_DATABASE: tutorial
    MYSQL_ROOT_PASSWORD: notsecure
    MYSLQ_CONTAINER_NAME: mysql

services:
    app:
        build:
            context: ..
            dockerfile: .devcontainer/Dockerfile
        environment:
            <<: *default-environment
            PORT: 3000
        ports:
            - 3000:3000
        volumes:
            - ..:/workspace
        user: vscode
        command: sleep infinity
    db:
        image: "mysql:8.0"
        restart: unless-stopped
        environment: *default-environment
        ports:
            - 3306:3306
        volumes:
            - pgdata:/var/lib/postgresql/data
            - ../mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
volumes:
    pgdata:
